
plugins{
    //kotlin("kapt")
    // apply plugin: 'com.android.library'
    alias(libs.plugins.android.library)

}
android {
    compileSdk = 28

    defaultConfig {
        minSdk = 28
        targetSdk = 28
    }
    buildTypes {
        release {
            minifyEnabled false
        }

        debug {
            minifyEnabled false
        }
    }
    namespace 'com.github.clans.fab'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}

dependencies {
}

