plugins{
  //kotlin("kapt")

  alias(libs.plugins.android.library)

}

android {
  compileSdk = 28
  resourcePrefix "cpv_"

  defaultConfig {
    minSdk = 28
    targetSdk = 28
  }
    namespace 'com.jaredrummler.android.colorpicker'
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_7
    targetCompatibility JavaVersion.VERSION_1_7
  }
}

dependencies {
  //noinspection GradleCompatible
  implementation 'androidx.legacy:legacy-support-v4:1.0.0'
}
